"""
Hypothesis data model for the fraud investigation system.
"""

from typing import TypedDict


class Hypothesis(TypedDict, total=False):
    """
    Competing explanation generated by the investigator.
    """

    id: str
    title: str
    description: str
    confidence: float
    supporting_evidence: list[str]
    contradicting_evidence: list[str]
