from typing import Any, TypedDict

try:
    from investigation.evidence import Evidence
except ImportError:
    class Evidence(TypedDict, total=False):
        id: str
        source: str
        type: str
        description: str
        data: dict[str, Any]
        confidence: float

try:
    from investigation.hypotheses import Hypothesis
except ImportError:
    class Hypothesis(TypedDict, total=False):
        id: str
        title: str
        description: str
        confidence: float
        supporting_evidence: list[str]
        contradicting_evidence: list[str]

try:
    from investigation.assessment import Assessment
except ImportError:
    class Assessment(TypedDict, total=False):
        verdict: str
        fraud_probability: float
        fraud_type: str | None
        exposure: float
        affected_txn_ids: list[str]
        supporting_evidence: list[str]
        contradicting_evidence: list[str]
        reasoning: str
        confidence: float

try:
    from schemas.decision import PolicyDecision
except ImportError:
    class PolicyDecision(TypedDict, total=False):
        actions: list[str]
        primary_action: str | None
        matched_rules: list[str]
        rationale: str
        requires_customer_response: bool
        evidence_requests: list[dict]
        exposure: float
        affected_txn_ids: list[str]
        customer_response_status: str | None
        policy_conflicts: list[str]



class InvestigationState(TypedDict, total=False):
    """
    Shared state passed through the fraud investigation workflow.

    The state connects:
        Case
          ↓
        Evidence
          ↓
        Hypotheses
          ↓
        Assessment
          ↓
        Policy
          ↓
        Final Decision
    """

    # ========================================================
    # CASE INFORMATION
    # ========================================================

    # Case-pack identifier
    case_id: str

    # Customer associated with the case
    customer_id: str

    # Card associated with the case
    card_id: str

    # Transaction that triggered the investigation
    flagged_txn_id: str

    # Case trigger metadata
    trigger_type: str | None
    trigger_text: str | None
    risk_score: float | None

    # ========================================================
    # CONVERSATION / MESSAGES
    # ========================================================

    # Message history for agent and tool interactions
    messages: list[Any]

    # ========================================================
    # INVESTIGATION
    # ========================================================

    # Concrete observations discovered during investigation
    evidence: list[Evidence]

    # Possible explanations generated by the investigator
    hypotheses: list[Hypothesis]

    # ========================================================
    # ASSESSMENT
    # ========================================================

    # Current overall assessment produced from the evidence
    # and competing hypotheses
    assessment: Assessment

    # ========================================================
    # EXTERNAL / MISSING EVIDENCE
    # ========================================================

    # Evidence that must be obtained outside the existing
    # dataset before a decision can be finalized.
    #
    # Examples:
    # - customer confirmation
    # - step-up authentication
    # - analyst review
    evidence_requests: list[dict]

    # ========================================================
    # POLICY / DECISION
    # ========================================================

    # Actions determined by the policy engine.
    #
    # Examples:
    # - CREATE_CASE
    # - VERIFY_WITH_CUSTOMER
    # - BLOCK_CARD
    # - CLOSE_NO_FRAUD
    # - FILE_REPORT
    # - MONITOR_CARD
    # - ESCALATE_TO_ANALYST
    actions: list[str]

    # Structured policy decision determined by the policy engine
    policy_decision: PolicyDecision

    # Customer communication response state ('unknown', 'confirmed', 'denied', 'no_response')
    customer_response_status: str | None

    # ========================================================
    # WORKFLOW CONTROL
    # ========================================================

    # Number of investigation cycles completed
    iteration_count: int

    # Maximum allowed cycles.
    # Safety mechanism against infinite agent loops.
    max_iterations: int

    # Whether the investigation should stop
    stop: bool

    # Explanation for why the workflow stopped
    stop_reason: str | None

    # ========================================================
    # OBSERVABILITY
    # ========================================================

    # Names of tools used during the investigation
    tools_used: list[str]

    # Errors encountered during the workflow
    errors: list[str]


def create_initial_state(
    case_id: str,
    customer_id: str,
    card_id: str,
    flagged_txn_id: str,
    trigger_type: str | None = None,
    trigger_text: str | None = None,
    risk_score: float | None = None,
    customer_response_status: str | None = None,
    **kwargs: Any,
) -> InvestigationState:
    """
    Create the initial state for a new investigation.
    """
    status = customer_response_status if customer_response_status is not None else "unknown"

    return {
        # Case
        "case_id": case_id,
        "customer_id": customer_id,
        "card_id": card_id,
        "flagged_txn_id": flagged_txn_id,
        "trigger_type": trigger_type,
        "trigger_text": trigger_text,
        "risk_score": risk_score,

        # Conversation
        "messages": [],

        # Investigation
        "evidence": [],
        "hypotheses": [],

        # Assessment
        "assessment": {},

        # External evidence
        "evidence_requests": [],

        # Policy
        "actions": [],
        "policy_decision": {},
        "customer_response_status": status,

        # Workflow
        "iteration_count": 0,
        "max_iterations": 10,

        "stop": False,
        "stop_reason": None,

        # Observability
        "tools_used": [],
        "errors": [],
    }